# Generated by Django 5.2.5 on 2026-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='doctors/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], max_length=20)),
            ],
        ),
    ]
